### ISSUE TITLE
osx build

### ISSUE THREAD

**Issue by mandria** [paperManu/splash#27]
hi, 
great project!

i'm trying to build on osx 10.10.5
during the make install i get this error

In file included from splash/splash/src/factory.cpp:11:
splash/splash/src/../include/./image_v4l2.h:32:10: fatal error: 
      'linux/videodev2.h' file not found
#include <linux/videodev2.h>

any suggestion?

**Comment by paperManu** [comment]
Hi mandria,
Thanks for the good words ;)
Indeed I did not disable v4l2 support when compiling on OSX. I'll fix this and close this thread once it's done.
I don't have time to verify support on OSX these days, so I really don't guarantee anything. But I'd be glad to fix any bug you could report.

**Comment by paperManu** [comment]
This should be fixed. I could not test it though.

**Comment by mandria** [comment]
i've cloned again the repo and tryed to build
same error

In file included from splash/splash/src/factory.cpp:11:
splash/src/../include/./image_v4l2.h:32:10: fatal error: 
      'linux/videodev2.h' file not found

**Comment by paperManu** [comment]
Did you switch to the develop branch ? The modification I made is still not in the release version (master branch).
```
git checkout develop
```

**Comment by mandria** [comment]
ah ok i'm sorry i didn't switch the branch
i'll let you know

**Comment by mandria** [comment]
ok now i'm compiling the develop branch,
i've got some other error now,
always during the make phase,


splash/splash/src/filter.cpp:219:40: error: non-constant-expression cannot be
      narrowed from type 'int' to 'size_type' (aka 'unsigned long') in initializer list
      [-Wc++11-narrowing]
    _filterUniforms["_time"] = Values({static_cast<int>(Timer::getTime() / 1000)});
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
splash/splash/src/filter.cpp:219:40: note: insert an explicit cast to silence
      this issue
    _filterUniforms["_time"] = Values({static_cast<int>(Timer::getTime() / 1000)});
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                       static_cast<size_type>(                  )
1 error generated.
make[2]: *** [src/CMakeFiles/splash-0.5.dir/filter.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/splash-0.5.dir/all] Error 2
make: *** [all] Error 2

**Comment by paperManu** [comment]
I just fixed the compilation issue. I still have issues running it on the Mac I have here, but I don't have time right now to fix it (and maybe it's only a local issue).

**Comment by mandria** [comment]
now the build complete successful, but i have some running issue too

**Comment by marcusnm10** [comment]
Hi could I get help for using splash I am doing a school project and I have to do some projection mapping but i am struggling on configuring splash

**Comment by mandria** [comment]
as paperManu told the osx build is in early development.
i can suggest yu to run the software on linux.
